# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MeasProd <- function(y, Meas, N, C, M, R, Prod) {
    .Call(`_glca_MeasProd`, y, Meas, N, C, M, R, Prod)
}

MeasProd1 <- function(y, Meas, N, C, M, R) {
    .Call(`_glca_MeasProd1`, y, Meas, N, C, M, R)
}

GetPost <- function(y, gamma, rho, Ng, G, C, M, R) {
    .Call(`_glca_GetPost`, y, gamma, rho, Ng, G, C, M, R)
}

GetUDPost <- function(y, delta, gamma, rho, Ng, G, W, C, M, R) {
    .Call(`_glca_GetUDPost`, y, delta, gamma, rho, Ng, G, W, C, M, R)
}

GetMLLike <- function(y, delta, gamma, rho, Ng, G, W, C, M, R) {
    .Call(`_glca_GetMLLike`, y, delta, gamma, rho, Ng, G, W, C, M, R)
}

GetUDPostX <- function(y, x, z, delta, gamma, rho, Ng, G, W, C, P, Q, M, R) {
    .Call(`_glca_GetUDPostX`, y, x, z, delta, gamma, rho, Ng, G, W, C, P, Q, M, R)
}

GetScore <- function(y, post, gamma, rho, Ng, G, C, M, R) {
    .Call(`_glca_GetScore`, y, post, gamma, rho, Ng, G, C, M, R)
}

GetScoreX <- function(y, x, post, gamma, rho, Ng, G, C, M, R, P, coeff_inv) {
    .Call(`_glca_GetScoreX`, y, x, post, gamma, rho, Ng, G, C, M, R, P, coeff_inv)
}

GetUDScore <- function(y, delta, gamma, rho, Ng, G, W, C, M, R) {
    .Call(`_glca_GetUDScore`, y, delta, gamma, rho, Ng, G, W, C, M, R)
}

GetUDScoreX <- function(y, x, z, delta, gamma, rho, Ng, G, W, P, Q, C, M, R, coeff_inv) {
    .Call(`_glca_GetUDScoreX`, y, x, z, delta, gamma, rho, Ng, G, W, P, Q, C, M, R, coeff_inv)
}

GetLik <- function(y, gamma, rho, Ng, G, C, M, R) {
    .Call(`_glca_GetLik`, y, gamma, rho, Ng, G, C, M, R)
}

GetFitted <- function(pattern, gamma, rho, N, C, M, R) {
    .Call(`_glca_GetFitted`, pattern, gamma, rho, N, C, M, R)
}

GetUDlik <- function(y, delta, gamma, rho, Ng, G, W, C, M, R) {
    .Call(`_glca_GetUDlik`, y, delta, gamma, rho, Ng, G, W, C, M, R)
}

GetUDfit <- function(pattern, delta, gamma_m, rho, N, W, C, M, R) {
    .Call(`_glca_GetUDfit`, pattern, delta, gamma_m, rho, N, W, C, M, R)
}

GetUDlikX <- function(y, delta, gamma, rho, Ng, G, W, C, M, R) {
    .Call(`_glca_GetUDlikX`, y, delta, gamma, rho, Ng, G, W, C, M, R)
}

GetDeriv <- function(post, x, gamma, N, C, P) {
    .Call(`_glca_GetDeriv`, post, x, gamma, N, C, P)
}

GetDeriv2 <- function(post, x, gamma, Ng, G, C, P) {
    .Call(`_glca_GetDeriv2`, post, x, gamma, Ng, G, C, P)
}

UpDelta <- function(PostW) {
    .Call(`_glca_UpDelta`, PostW)
}

UpGammaML <- function(PostW, W, C) {
    .Call(`_glca_UpGammaML`, PostW, W, C)
}

UpGamma <- function(Post, Ng, G, C) {
    .Call(`_glca_UpGamma`, Post, Ng, G, C)
}

UpRhoU <- function(y, Post, rho, Ng, G, C, M, R) {
    .Call(`_glca_UpRhoU`, y, Post, rho, Ng, G, C, M, R)
}

UpRhoR <- function(y, Post, rho, Ng, G, C, M, R) {
    .Call(`_glca_UpRhoR`, y, Post, rho, Ng, G, C, M, R)
}

UpRhoML <- function(y, PostC, rho, Ng, G, C, M, R) {
    .Call(`_glca_UpRhoML`, y, PostC, rho, Ng, G, C, M, R)
}

ObsCell <- function(y, N, M, R, maxiter, eps) {
    .Call(`_glca_ObsCell`, y, N, M, R, maxiter, eps)
}

ObsLik <- function(y, N, M, R, maxiter, eps) {
    .Call(`_glca_ObsLik`, y, N, M, R, maxiter, eps)
}

ObsCell2 <- function(sy, u, N, U) {
    .Call(`_glca_ObsCell2`, sy, u, N, U)
}

